---
title: "D2SC ICMA Notebook"
output: html_notebook
author: "Jennifer Curi"
date: "`r Sys.Date()`"

---

# ICMA September 9 2024

```{r}

# this is a comment
plot(cars)
```

# ICMA September 11 2024
```{r}

2+2

```

```{r}

x <- 2+2

```

```{r}

x 

```
```{r}

?(mean)

```


```{r}

help(mean)

```

```{r}

mean(c(2,3,4))

```

```{r}

myVector <- (c(2,3,4))

```

```{r}

mean(my_vector)

```
doesnt initialize until after it is veab used

```{r}

my_vector <- (c(2,3,4))

```

```{r}

myVector

```

```{r}

?sd
help(sd)

```

```{r}

sd(1:2) ^2

```



# ICMA September 16 2024

```{r}
library(tidyverse)
```

```{r}

stats::filter()

```

```{r}
head(3, billboard)
#does not work
```

```{r}

#pipe -> takes outcome and passes it to the next function 


```

```{r}
#create a vector of num

my_numbers <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
```

```{r}

#without pipe
mean(my_numbers)


```


```{r}
my_numbers %>%
  mean()
```



```{r}
getwd()

#working directory
```


```{r}
help(mtcars)
#description of dataset
```


```{r}
mtcars
```






```{r}
write_csv(mtcars, #object name
          "mtcars_fromR.csv" #file name to save
          )
#writing data set
#no columns
```

```{r}
mtcars %>%
  rownames_to_column() %>%
  write_csv("mtcars_fromR_rownames.csv")

#adds columns
```


```{r}
mtcars_read <- read_csv("data/mtcars_fromR_rownames.csv")

#read csv
#assign as a variable

```

# ICMA September 18 2024

```{r}
? ChickWeight
```

```{r}
glimpse(ChickWeight)
```

```{r}
ChickWeight %>%
  select(Chick,weight) %>% #keep Chick and Weight
  head(n=3) #view just three rows
```

```{r}
ChickWeight %>%
  select(age_days = Time, weight_gm = weight) %>% #renaming while keeping
  head(n=3)
```

```{r}
ChickWeight %>%
  select(-weight) %>% #drop a column
  head(n=3)
```

```{r}
#will not change original object
ChickWeight %>%
  select(age_days = Time, weight_gm = weight) %>%
  head() #to restrict preview
```

```{r}
#will replace original object
ChickWeight <- ChickWeight %>%
  select(age_days = Time, weight_gm = weight)
```

```{r}
#will save the modified object in a new object
ChickWeightModified <- ChickWeight %>%
  select(age_days = Time, weight_gm = weight)
```

```{r}
chick_clean <- ChickWeight %>% #assigning to a new object chick_clean
  select(chick_id = Chick,
         diet = Diet,
         age_days = Time,
         weight_gm = weight) #renaming %re-ordering while keeping
```

```{r}
chick_clean %>%
  filter(age_days <10) %>%
  head(n = 6)
```


```{r}
chick_clean %>%
  filter(chick_id == 1) %>%
  head(n = 6)
```

```{r}
chick_clean %>%
  distinct(chick_id) %>%
  glimpse()
```

```{r}
chick_clean %>%
  arrange(age_days) %>%
  head() # just for preview
```


```{r}
chick_clean %>%
  arrange(chick_id) %>%
  head() # just for preview
```


```{r}
chick_clean %>%
  mutate(new_column = "value") %>%
  head(n = 3)
```

```{r}
chick_clean %>%
  mutate(weight_per_day = weight_gm/age_days) %>%
  head(n = 3)
```


```{r}
chick_clean %>%
  mutate(session = case_when(age_days == 0 ~ "birth",
                             age_days == 20 ~ "last1",
                             age_days == 21 ~ "last2",
                             TRUE           ~ as.character(age_days)))
```


```{r}
chick_clean %>%
  summarise(mean_weight = mean(weight_gm),
            N = n())
```


```{r}
chick_clean %>%
  group_by(age_days) %>% ## grouping variable
  summarise(mean_weight = mean(weight_gm),
            N = n()) ## creates a column that summarizes the data based on the grouping variable

```

```{r}
grouped <- chick_clean %>%
  group_by(age_days)
```
```{r}
chick_clean %>%
  glimpse()
```

```{r}
grouped %>%
  glimpse()
```

```{r}
chick_clean %>%
  summarise(mean_weight = mean(weight_gm))

```

```{r}
grouped %>%
  summarise(mean_weight = mean(weight_gm))
```

```{r}
grouped %>%
  ungroup() %>%
  summarise(mean_weight = mean(weight_gm))
```

```{r}
ChickWeight %>%
  distinct(Chick) %>%
  count() %>%
  head(n=3)
```






# ICMA September 23 2024

```{r}
head(billboard)
```

```{r}
billboard %>%
  pivot_longer(wk1:wk76)

```

```{r}
billboard_long <- billboard %>%
  pivot_longer(cols=starts_with("wk"),
               names_to = "week",
               values_to = "position")

```


```{r}
head(billboard_long)
```
```{r}
dim(billboard)
```

```{r}
billboard_long %>%
  pivot_wider(names_from = week,
              values_from = position)
```

```{r}
?pivot_longer
```


```{r}
billboard %>%
  pivot_longer(cols=starts_with("wk"),
               names_to = "week",
               values_to = "position",
               names_prefix = "wk",
               values_drop_na = TRUE)
```


```{r}
billboard %>%
  separate(col = date.entered,
          into = c("year", "month", "day"))
             
```




