clear all
close all
clc


%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\luigi\Desktop\Research\PhD\gender_differences\DB.csv
%
% Auto-generated by MATLAB on 12-Jan-2023 15:32:17

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "CS", "res", "nres", "trial", "rt", "hrv", "ID"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "ID", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["CS", "ID"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "res", "TrimNonNumeric", true);
opts = setvaropts(opts, "res", "ThousandsSeparator", ",");

% Import the data
tbl = readtable("C:\Users\luigi\OneDrive - Alma Mater Studiorum Università di Bologna\Desktop\Research\PhD\gender_differences\DB.csv", opts);

%% Convert to output type
VarName1 = tbl.VarName1;
CS = tbl.CS;
res = tbl.res;
nres = tbl.nres;
trial = tbl.trial;
tr = tbl.rt;
hrv = tbl.hrv;
ID = tbl.ID;


subj=unique(ID);
for zz=1:length(subj)
    IDindex(:,1)=find(ID==subj(zz));
    cs{:,zz}=CS(IDindex);
    response{:,zz}=res(IDindex);
    nresponse{:,zz}=nres(IDindex);
    trials{:,zz}=trial(IDindex);
    rt{:,zz}=tr(IDindex);
    clear IDindex
end

%%Clear temporary variables
clear opts tbl CS res nres trial


%% EXCLUSION RT OUTLIERS (+-2 SD from the mean for each subj)
for zz=1:length(subj)
    meanCS=mean(rt{:,zz});
    stdCS=std(rt{:,zz});
    indexnooutliers=find(rt{:,zz}>(meanCS-2*stdCS) & rt{:,zz}<(meanCS+2*stdCS));
    rtNOoutilers{:,zz}=rt{:,zz}(indexnooutliers,:);
    csNOoutilers{:,zz}=cs{:,zz}(indexnooutliers,:);
    typeNOoutilers{:,zz}=response{:,zz}(indexnooutliers,:);
    clear meanCS stdCS indexnooutliers
end

%% REACTION TIME ANALYSIS
%%Separate for CSm, CS1, CS2, CS3 for each subj OUTLIERS EXCLUDED
for zz=1:length(subj)
    CSmindex(:,1)=find(csNOoutilers{:,zz}=="CS-");
    CS1index(:,1)=find(csNOoutilers{:,zz}=="CS1");
    CS2index(:,1)=find(csNOoutilers{:,zz}=="CS2");
    CS3index(:,1)=find(csNOoutilers{:,zz}=="CS3");
    
    %cs
    CSm{:,zz}=csNOoutilers{:,zz}(CSmindex,:);
    CS1{:,zz}=csNOoutilers{:,zz}(CS1index,1);
    CS2{:,zz}=csNOoutilers{:,zz}(CS2index,1);
    CS3{:,zz}=csNOoutilers{:,zz}(CS3index,1);
    
    %rt
    rtCSm{:,zz}=rtNOoutilers{:,zz}(CSmindex,:);
    rtCS1{:,zz}=rtNOoutilers{:,zz}(CS1index,1);
    rtCS2{:,zz}=rtNOoutilers{:,zz}(CS2index,1);
    rtCS3{:,zz}=rtNOoutilers{:,zz}(CS3index,1);
    
    %typeofresponse
    typeCSm{:,zz}=typeNOoutilers{:,zz}(CSmindex,1);
    typeCS1{:,zz}=typeNOoutilers{:,zz}(CS1index,1);
    typeCS2{:,zz}=typeNOoutilers{:,zz}(CS2index,1);
    typeCS3{:,zz}=typeNOoutilers{:,zz}(CS3index,1);   
    
    CSmR1index=find(typeCSm{:,zz}==1);
    CSmR2index=find(typeCSm{:,zz}==2);
    CS1R1index=find(typeCS1{:,zz}==1);
    CS1R2index=find(typeCS1{:,zz}==2);
    CS2R1index=find(typeCS2{:,zz}==1);
    CS2R2index=find(typeCS2{:,zz}==2);
    CS3R1index=find(typeCS3{:,zz}==1);
    CS3R2index=find(typeCS3{:,zz}==2);
    rtpercs(zz,:)=[subj(zz,1) mean(rtCS1{:,zz}) mean(rtCS2{:,zz}) mean(rtCS3{:,zz}) mean(rtCSm{:,zz})];
    rtPERresp(zz,:)=[subj(zz,1) mean(rtCS1{:,zz}(CS1R1index,:)) mean(rtCS1{:,zz}(CS1R2index,:)) mean(rtCS2{:,zz}(CS2R1index,:)) mean(rtCS2{:,zz}(CS2R2index,:)) mean(rtCS3{:,zz}(CS3R1index,:)) mean(rtCS3{:,zz}(CS3R2index,:)) mean(rtCSm{:,zz}(CSmR1index,:)) mean(rtCSm{:,zz}(CSmR2index,:))];
    
    clear CSmindex CS1index CS2index CS3index CSmR1index CSmR1index CS1R1index CS1R2index CS2R1index CS2R2index CS3R1index CS3R2index 
    
%     %reaction times without type of response division
%     reaction_times(zz,1)=mean(rtCSm{:,zz});
%     reaction_times(zz,2)=mean(rtCS1{:,zz});
%     reaction_times(zz,3)=mean(rtCS2{:,zz});
%     reaction_times(zz,4)=mean(rtCS3{:,zz});
end
  
% reaction_times=[reaction_times subj];


%% RESPONSE ANALYSIS
%%Separate for CSm, CS1, CS2, CS3 for each subj (there are no outlier)
for zz=1:length(subj)
    CSmindex(:,1)=find(cs{:,zz}=="CS-");
    CS1index(:,1)=find(cs{:,zz}=="CS1");
    CS2index(:,1)=find(cs{:,zz}=="CS2");
    CS3index(:,1)=find(cs{:,zz}=="CS3");
    
    %cs
    CSm{:,zz}=cs{:,zz}(CSmindex,:);
    CS1{:,zz}=cs{:,zz}(CS1index,1);
    CS2{:,zz}=cs{:,zz}(CS2index,1);
    CS3{:,zz}=cs{:,zz}(CS3index,1);
    
    %type of resp
    typeCSm{:,zz}=response{:,zz}(CSmindex,1);
    typeCS1{:,zz}=response{:,zz}(CS1index,1);
    typeCS2{:,zz}=response{:,zz}(CS2index,1);
    typeCS3{:,zz}=response{:,zz}(CS3index,1);
    
    %response
    respCSm{:,zz}=nresponse{:,zz}(CSmindex,:);
    respCS1{:,zz}=nresponse{:,zz}(CS1index,1);
    respCS2{:,zz}=nresponse{:,zz}(CS2index,1);
    respCS3{:,zz}=nresponse{:,zz}(CS3index,1);
    
    clear CSmindex CS1index CS2index CS3index
    

    
    CSmR1index=find(typeCSm{:,zz}==1);
    CSmR2index=find(typeCSm{:,zz}==2);
    CS1R1index=find(typeCS1{:,zz}==1);
    CS1R2index=find(typeCS1{:,zz}==2);
    CS2R1index=find(typeCS2{:,zz}==1);
    CS2R2index=find(typeCS2{:,zz}==2);
    CS3R1index=find(typeCS3{:,zz}==1);
    CS3R2index=find(typeCS3{:,zz}==2);
    
    nrespPERresp(zz,:)=[mean(respCS1{:,zz}(CS1R1index,:)) mean(respCS1{:,zz}(CS1R2index,:)) mean(respCS2{:,zz}(CS2R1index,:)) mean(respCS2{:,zz}(CS2R2index,:)) mean(respCS3{:,zz}(CS3R1index,:)) mean(respCS3{:,zz}(CS3R2index,:)) mean(respCSm{:,zz}(CSmR1index,:)) mean(respCSm{:,zz}(CSmR2index,:))];
    sumrespPERresp(zz,:)=[sum(respCS1{:,zz}(CS1R1index,:)) sum(respCS1{:,zz}(CS1R2index,:)) sum(respCS2{:,zz}(CS2R1index,:)) sum(respCS2{:,zz}(CS2R2index,:)) sum(respCS3{:,zz}(CS3R1index,:)) sum(respCS3{:,zz}(CS3R2index,:)) sum(respCSm{:,zz}(CSmR1index,:)) sum(respCSm{:,zz}(CSmR2index,:))];
    clear CSmindex CS1index CS2index CS3index CSmR1index CSmR1index CS1R1index CS1R2index CS2R1index CS2R2index CS3R1index CS3R2index 
    
%% for first half of trials
    %consider only the first  half of trials
    countCSm=round(size(CSm{:,zz},1)/2);
    countCS1=round(size(CS1{:,zz},1)/2);
    countCS2=round(size(CS2{:,zz},1)/2);
    countCS3=round(size(CS3{:,zz},1)/2);
    
    %type of resp
    typeCSm{:,zz}=typeCSm{:,zz}(1:countCSm,:);
    typeCS1{:,zz}=typeCS1{:,zz}(1:countCS1,:);
    typeCS2{:,zz}=typeCS2{:,zz}(1:countCS2,:);
    typeCS3{:,zz}=typeCS3{:,zz}(1:countCS3,:);
    
    %response
    respCSm{:,zz}=respCSm{:,zz}(1:countCSm,:);
    respCS1{:,zz}=respCS1{:,zz}(1:countCS1,:);
    respCS2{:,zz}=respCS2{:,zz}(1:countCS2,:);
    respCS3{:,zz}=respCS3{:,zz}(1:countCS3,:);
    
    %clear CSmindex CS1index CS2index CS3index
    
    
    CSmR1index=find(typeCSm{:,zz}==1);
    CSmR2index=find(typeCSm{:,zz}==2);
    CS1R1index=find(typeCS1{:,zz}==1);
    CS1R2index=find(typeCS1{:,zz}==2);
    CS2R1index=find(typeCS2{:,zz}==1);
    CS2R2index=find(typeCS2{:,zz}==2);
    CS3R1index=find(typeCS3{:,zz}==1);
    CS3R2index=find(typeCS3{:,zz}==2);
    
    half_nrespPERresp(zz,:)=[mean(respCSm{:,zz}(CSmR1index,:)) mean(respCSm{:,zz}(CSmR2index,:)) mean(respCS1{:,zz}(CS1R1index,:)) mean(respCS1{:,zz}(CS1R2index,:)) mean(respCS2{:,zz}(CS2R1index,:)) mean(respCS2{:,zz}(CS2R2index,:)) mean(respCS3{:,zz}(CS3R1index,:)) mean(respCS3{:,zz}(CS3R2index,:))];
 
    clear CSmindex CS1index CS2index CS3index CSmR1index CSmR1index CS1R1index CS1R2index CS2R1index CS2R2index CS3R1index CS3R2index 
        
end



